#!/bin/bash

if [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "feature/travis-support" ]; then
  ENV=test;
  TAG="$ENV-$TRAVIS_COMMIT";
  docker login --username="$DOCKER_USER" --password="$DOCKER_PASS";
  docker tag floq "blankoslo/floq:$TAG";
  docker push "blankoslo/floq:$TAG";
  export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json";
  kubectl set image deployment/floq-blank-$ENV "floq-blank-$ENV=blankoslo/floq:$TAG";
fi

