#!/bin/bash

if [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "feature/travis-support" ]; then
  ENV=test;
elif [ "$TRAVIS_BRANCH" == "master" ]; then
  ENV=prod;
else
  unset ENV;
fi

if ! [ -z "$ENV" ]; then
  TAG="$ENV-$TRAVIS_COMMIT";
  docker login --username="$DOCKER_USER" --password="$DOCKER_PASS";
  docker tag floq "blankoslo/floq:$TAG";
  docker push "blankoslo/floq:$TAG";
  docker tag floq "blankoslo/floq:$ENV";
  docker push "blankoslo/floq:$ENV";
  export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json";
  "$HOME/google-cloud-sdk/bin/kubectl" \
    set image deployment/floq-blank-$ENV \
    "floq-blank-$ENV=blankoslo/floq:$TAG" \
    --namespace="floq-blank-${ENV}";
fi

