#!/bin/bash

if [ ! -d "${HOME}/google-cloud-sdk" ]; then
  curl https://sdk.cloud.google.com | bash;
fi

export PATH=${HOME}/google-cloud-sdk/bin:$PATH

gcloud auth activate-service-account --key-file client-secret.json
gcloud components update
gcloud components install kubectl
gcloud config set container/cluster floq
gcloud config set compute/zone europe-west1-b
gcloud config set project marine-cycle-97212
gcloud container clusters get-credentials floq

